apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# beginning of customizations
resources:
  - console-service-account.yaml
  - console-cluster-role.yaml
  - console-cluster-role-binding.yaml
  - console-configmap.yaml
  - console-service.yaml
  - console-deployment.yaml
