name: "Delta Lake Tests"
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        scala: [2.12.14, 2.13.5]
    env:
      SCALA_VERSION: ${{ matrix.scala }}
    steps:
      - uses: actions/checkout@v2
      - name: install java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Cache Scala, SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2
            ~/.cache/coursier
          # Change the key if dependencies are changed. For each key, GitHub Actions will cache the
          # the above directories when we use the key for the first time. After that, each run will
          # just use the cache. The cache is immutable so we need to use a new key when trying to
          # cache new stuff.
          key: delta-sbt-cache-spark3.2-scala${{ matrix.scala }}
      - name: Install Job dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl git
          sudo apt install libedit-dev
          sudo apt install python3-pip --fix-missing
          sudo pip3 install pipenv==2021.5.29
          curl https://pyenv.run | bash
          export PATH="~/.pyenv/bin:$PATH"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          pyenv install 3.7.4
          pyenv global system 3.7.4
          pipenv --python 3.7 install
          pipenv run pip install pyspark==3.2.0
          pipenv run pip install flake8==3.5.0 pypandoc==1.3.3
          pipenv run pip install importlib_metadata==3.10.0
          pipenv run pip install mypy==0.910
      - name: Run Scala/Java and Python tests
        run: |
          pipenv run python run-tests.py
