name: Move updated pull requests to Needs Review

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [synchronize]

jobs:
  automate-updated-pull-requests:
    if: ${{ (github.event.issue.pull_request || github.event.pull_request) &&
            !contains('allisonport-db dennyglee scottsand-db tdas vkorukanti zsxwing', github.event.sender.login) &&
            (github.event.pull_request.state == 'open' || github.event.issue.state == 'open') }}
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@2af3cf061aeca8ac6ab40a960eee1968a7f9ce0e # TODO: update to use a version after fixes are merged & released
        with:
          project: oss-delta-prs
          column: Needs Review
          repo-token: ${{ secrets.PROJECT_BOARD_AUTOMATION_TOKEN }}
